export const NO_ORGANIZATION_FAKE_ID = 'NO_ORGANIZATION_FAKE_ID' // This is not in database, only to manipulate personnal project

export const ORGANIZATION_USER_ROLE_EDITOR = 'Editor'
export const ORGANIZATION_USER_ROLE_VIEWER = 'Viewer'
export const ORGANIZATION_USER_ROLE_ADMIN = 'Admin'
export const ORGANIZATION_USER_ROLE_OWNER = 'Owner'

export const ORGANIZATION_ROLE_ID = {
    [ORGANIZATION_USER_ROLE_OWNER]: 'ownerUserId',
    [ORGANIZATION_USER_ROLE_ADMIN]: 'adminUserIds',
    [ORGANIZATION_USER_ROLE_EDITOR]: 'editorUserIds',
    [ORGANIZATION_USER_ROLE_VIEWER]: 'viewerUserIds',
}

export const ORGANIZATION_NEW_USER_ROLES = [
    ORGANIZATION_USER_ROLE_VIEWER,
    ORGANIZATION_USER_ROLE_EDITOR,
    ORGANIZATION_USER_ROLE_ADMIN,
]

export const ORGANIZATION_EXISTING_USER_ROLES = [
    ...ORGANIZATION_NEW_USER_ROLES,
    ORGANIZATION_USER_ROLE_OWNER,
]
