export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS'
export const GET_SESSION_ERROR = 'GET_SESSION_ERROR'
export const SET_SESSION_FILTER = 'SET_SESSION_FILTER'
export const SET_SELECTED_SESSION = 'SET_SELECTED_SESSION'
