export const GET_USER_DETAILS_SUCCESS = 'admin/users/get/success'
export const USERS_SET_FILTER = 'admin/users/filter/set'
export const USER_INVITE_GET_SUCCESS = 'admin/users/invite/get/success'
export const USER_INVITE_ADD = 'admin/users/invite/add'
export const USER_INVITE_REMOVE_SUCCESS = 'admin/users/invite/remove/success'
export const USER_INVITES_GET_SUCCESS = 'admin/users/invites/get/success'
