version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@nivo/core"
    versions:
    - ">= 0.65.a, < 0.66"
  - dependency-name: "@nivo/core"
    versions:
    - ">= 0.66.a, < 0.67"
  - dependency-name: "@nivo/core"
    versions:
    - ">= 0.67.a, < 0.68"
  - dependency-name: "@nivo/line"
    versions:
    - ">= 0.65.a, < 0.66"
  - dependency-name: "@nivo/line"
    versions:
    - ">= 0.66.a, < 0.67"
  - dependency-name: "@nivo/line"
    versions:
    - ">= 0.67.a, < 0.68"
  - dependency-name: "@date-io/luxon"
    versions:
    - 2.10.6
    - 2.10.8
  - dependency-name: react-helmet-async
    versions:
    - 1.0.8
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.19
    - 6.1.20
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.19
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.1.19
  - dependency-name: firebase
    versions:
    - 8.2.9
  - dependency-name: yup
    versions:
    - 0.32.9
  - dependency-name: i18next
    versions:
    - 19.8.5
    - 19.8.8
  - dependency-name: firebase-tools
    versions:
    - 9.3.0
    - 9.4.0
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - "> 4.19.1"
  - dependency-name: firebase-tools
    versions:
    - 9.5.0
  - dependency-name: form-data
    versions:
    - 4.0.0
  - dependency-name: firebase
    versions:
    - 8.2.5
    - 8.2.7
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: ts-jest
    versions:
    - 26.5.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
