export const GET_PROJECTS_SUCCESS = 'admin/getProjects/success'
export const GET_PROJECTS_ERROR = 'admin/getProjects/error'
export const SELECT_PROJECT = 'admin/selectProject'
export const GET_PROJECT_VOTE_ITEMS_SUCCESS = 'admin/getProjectVoteItem/success'
export const GET_PROJECT_VOTE_ITEMS_ERROR = 'admin/getProjectVoteItem/error'
