export const GET_SESSION_VOTES_SUCCESS = 'admin/getSessionVotes/success'
export const GET_SESSION_VOTES_ERROR = 'admin/getSessionVotes/error'
export const CLEAR_SESSION_VOTES = 'admin/clearSessionVotes'
export const GET_USER_VOTES_SUCCESS = 'admin/getUserVotes/success'
export const GET_USER_VOTES_ERROR = 'admin/getUserVotes/error'
export const CLEAR_USER_VOTES = 'admin/clearUserVotes'
