export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR'
export const GET_PROJECT_VOTE_ITEMS_SUCCESS = 'GET_PROJECT_VOTE_ITEMS_SUCCESS'
export const GET_PROJECT_VOTE_ITEMS_ERROR = 'GET_PROJECT_VOTE_ITEMS_ERROR'
