export const VOTE_STATUS_ACTIVE = 'active'
export const VOTE_STATUS_DELETED = 'deleted'
export const VOTE_STATUS_HIDDEN = 'hidden'
export const VOTE_TYPE_BOOLEAN = 'boolean'
export const VOTE_TYPE_TEXT = 'text'
