export const GET_SPEAKER_SUCCESS = 'GET_SPEAKER_SUCCESS'
export const GET_SPEAKER_ERROR = 'GET_SPEAKER_ERROR'
export const GET_SPEAKERS_SUCCESS = 'GET_SPEAKERS_SUCCESS'
export const GET_SPEAKERS_ERROR = 'GET_SPEAKERS_ERROR'
