name: Build project + unit test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
    - name: move to function, init & run test
      run: |
        cd functions
        cp serviceAccountKey.json.example serviceAccountKey.json
        npm install
        npm run build --if-present
        npm run test
    - name: run lighthouse ci
      run: |
          npm install -g @lhci/cli@0.3.x
          pwd
          ls -la
          lhci autorun --config=./lighthouserc.json
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
