name: Build project + unit test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: 'npm'
    - name: npm install (ci)
      run: |
        npm ci
    - name: npm build
      run: |
        npm run build
    - name: npm lint:i18n
      run: |
        npm run lint:i18n
    - name: npm test & test functions/
      run: |
        npm run test
    - name: move to function, install & build
      run: |
        cd functions
        npm ci
        npm run build --if-present
#        npm run test # Already done from root
    - name: run lighthouse ci
      run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --config=./lighthouse/lighthouserc.json
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
