name: Run End to End test using Cypress

on:
    push:
    pull_request:
    pull_request_target:
    workflow_dispatch:

jobs:
  cypress-run:
    name: Run End to end test using Cypress
    runs-on: ubuntu-latest
    if:
        (github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'dependabot[bot]') ||
        (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]') ||
        github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Check for secrets
      env:
        SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
      shell: pwsh
      run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
    - name: Checkout
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v2.4.0
    - name: Checkout for Dependabot
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v2.4.0
      with:
        ref: 'refs/pull/${{ github.event.number }}/merge'
    - name: Setup Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: "Create .runtimeconfig.json"
      run: 'echo "$RUNTIME_CONFIG_TEST" > functions/.runtimeconfig.json'
      shell: bash
      env:
          RUNTIME_CONFIG_TEST: ${{secrets.RUNTIME_CONFIG_TEST}}
    - name: "test"
      run: 'cat functions/.runtimeconfig.json'
      shell: bash
    - name: Install functions dependencies
      run: |
            cd functions
            npm ci
            npm run build
    - name: Run Cypress E2E test
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm run cy:start:ci -- --token=${{ secrets.CYPRESS_FIREBASE_TOKEN }} --project open-feedback-cypress, npx firebase serve --only hosting -p 3000 --token=${{ secrets.CYPRESS_FIREBASE_TOKEN }}
        wait-on: 'http://localhost:3000, http://localhost:8080, http://localhost:9099'
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
        REACT_APP_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        REACT_APP_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        REACT_APP_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
        CYPRESS_REACT_APP_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        CYPRESS_REACT_APP_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        CYPRESS_REACT_APP_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        CYPRESS_REACT_APP_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        CYPRESS_REACT_APP_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
        REACT_APP_EMULATORS: true
        EMULATORS_NAMES: "firestore,auth,functions"
