name: Run End to End test using Cypress

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: set env variables
      run: |
          echo 'export REACT_APP_API_KEY="$E2E_FIREBASE_API_KEY"' >> $BASH_ENV
          echo 'export REACT_APP_AUTH_DOMAIN="$E2E_FIREBASE_AUTH_DOMAIN"' >> $BASH_ENV
          echo 'export REACT_APP_PROJECT_ID="$E2E_FIREBASE_PROJECT_ID"' >> $BASH_ENV
          echo 'export REACT_APP_DATABASE_URL="$E2E_FIREBASE_DATABASE_URL"' >> $BASH_ENV
    - name: npm install, build
      run: |
        npm install
        npm run build
        ./node_modules/.bin/firebase serve --only hosting -p 3000  --token=${{ secrets.CYPRESS_FIREBASE_TOKEN }} &
        npx wait-on http://localhost:3000
    - name: Run Cypress
      run: |
          ./node_modules/.bin/cypress run --record --key ${{ secrets.CYPRESS_DASHBOARD_KEY }}
      env:
        CI: true
