name: Run End to End test using Cypress

on: [push, pull_request]

jobs:
  cypress-run:
    name: Run End to end test using Cypress
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: "Create .runtimeconfig.json"
      run: 'echo "$RUNTIME_CONFIG_TEST" > functions/.runtimeconfig.json'
      shell: bash
      env:
          RUNTIME_CONFIG_TEST: ${{secrets.RUNTIME_CONFIG_TEST}}
    - name: "test"
      run: 'cat functions/.runtimeconfig.json'
      shell: bash
    - name: Install functions dependencies
      run: |
            cd functions
            npm ci
            npm run build
    - name: Run Cypress E2E test
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm run cy:start:ci -- --token=${{ secrets.CYPRESS_FIREBASE_TOKEN }} --project open-feedback-cypress, npx firebase serve --only hosting -p 3000 --token=${{ secrets.CYPRESS_FIREBASE_TOKEN }}
        wait-on: 'http://localhost:3000, http://localhost:8080, http://localhost:9099'
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
        VITE_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        VITE_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        VITE_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        VITE_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        VITE_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
        CYPRESS_VITE_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        CYPRESS_VITE_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        CYPRESS_VITE_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        CYPRESS_VITE_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        CYPRESS_VITE_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
        VITE_EMULATORS: true
        EMULATORS_NAMES: "firestore,auth,functions"
