name: Run End to End test using Cypress

on: [push]

jobs:
  cypress-run:
    name: Run End to end test using Cypress
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
          node-version-file: .nvmrc
          cache: 'npm'
    - name: "Create .runtimeconfig.json"
      run: 'echo "$RUNTIME_CONFIG_TEST" > functions/.runtimeconfig.json'
      shell: bash
      env:
          RUNTIME_CONFIG_TEST: ${{secrets.RUNTIME_CONFIG_TEST}}
    - name: "test"
      run: 'cat functions/.runtimeconfig.json'
      shell: bash
    - name: Install functions dependencies
      run: |
            cd functions
            npm ci
            npm run build
    - name: Change .firebaserc file to use open-feedback-cypress project ID
      run: |
                sed -i 's/open-feedback-42/open-feedback-cypress/g' .firebaserc
                cat .firebaserc
    - name: Run Cypress E2E test
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm run cy:start
        wait-on: 'http://localhost:3000, http://localhost:8080, http://localhost:9099'
        record: true
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.E2E_GCLOUD_CREDENTIAL_OPEN_FEEDBACK_CYPRESS }}
        VITE_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        VITE_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        VITE_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        VITE_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        VITE_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
        VITE_EMULATORS: true
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
        CYPRESS_VITE_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        CYPRESS_VITE_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        CYPRESS_VITE_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        CYPRESS_VITE_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        CYPRESS_VITE_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
