name: Run End to End test using Cypress

on: [push]

jobs:
  cypress-run:
    name: Run End to end test using Cypress
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install functions dependencies
      run: |
            cd functions
            npm ci
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm run cy:start:ci -- --token=${{ secrets.CYPRESS_FIREBASE_TOKEN }} --project open-feedback-cypress, npx firebase serve --only hosting -p 3000 --token=${{ secrets.CYPRESS_FIREBASE_TOKEN }}
        wait-on: 'http://localhost:3000, http://localhost:5001, http://localhost:8080, http://localhost:9099'
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
        REACT_APP_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        REACT_APP_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        REACT_APP_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
        CYPRESS_REACT_APP_APPID: ${{ secrets.E2E_FIREBASE_APPID }}
        CYPRESS_REACT_APP_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
        CYPRESS_REACT_APP_AUTH_DOMAIN: ${{ secrets.E2E_FIREBASE_AUTH_DOMAIN }}
        CYPRESS_REACT_APP_DATABASE_URL: ${{ secrets.E2E_FIREBASE_DATABASE_URL }}
        CYPRESS_REACT_APP_PROJECT_ID: ${{ secrets.E2E_FIREBASE_PROJECT_ID }}
        REACT_APP_EMULATORS: true
        EMULATORS_NAMES: "firestore,auth,functions"
